### ISSUE TITLE
GitBucket supports editorconfig

### ISSUE THREAD

**Issue by kounoike** [editorconfig/editorconfig.github.com#100]
[GitBucket](https://github.com/gitbucket/gitbucket) is repository manager like GitHub/Gogs.
It supports editorconfig in repository browser/editor by my [PR](https://github.com/gitbucket/gitbucket/pull/1966). It doesn't require any plugin. Could you add GitBucket into supported editors list?

- Homepage: https://github.com/gitbucket/gitbucket or https://gitbucket.github.io/
- Logo: https://github.com/gitbucket/gitbucket/blob/master/src/main/webapp/assets/common/images/gitbucket.svg

**Comment by xuhdev** [comment]
Oops, sorry, I overlooked this issue. @Pittan Can you help out again? Thanks! :smile:
