### ISSUE TITLE
Incorrect link of EditorConfig support in Visual Studio

### ISSUE THREAD

**Issue by xuhdev** [editorconfig/editorconfig.github.com#107]
Visual Studio, as listed on the website, should have builtin support. However, we pointed it to a plugin website. Can someone pointing me to the information page which states that EditorConfig is supported as a builtin feature in Visual Studio? I've had a hard time finding it. Thanks!

**Comment by jedmao** [comment]
And it's only partially built-in supported, from what I understand. I do remember reading that a while back... somewhere...

**Comment by ffes** [comment]
It is in the release notes for VS2017

https://docs.microsoft.com/en-us/visualstudio/releasenotes/vs2017-relnotes-v15.0#coding-convention-support-through-editorconfig
