### ISSUE TITLE
Working Copy supports .editorconfig without a plugin

### ISSUE THREAD

**Issue by palmin** [editorconfig/editorconfig.github.com#108]
Working Copy is a Git client for iOS with a built-in editor that supports .editorconfig without a plugin.

https://workingcopy.app/

You can find the logo/icon at https://workingcopy.app/img/working-copy.png but unfortunately not in the style used by editorconfig.org

I'm the only developer of the app.

**Comment by xuhdev** [comment]
@Pittan Can you help again? Thanks! :smiley:

**Comment by palmin** [comment]
Would it help if I provided an image to use?

My girlfriend could probably make something very close to the style of the other logos.

**Comment by Pittan** [comment]
Sorry!  I overeloooked the notification :bow:

**Comment by xuhdev** [comment]
Either way is OK :) Feel free to make a PR when it's ready! (For license issues, please do so!)

**Comment by palmin** [comment]
There is an PR #123 with image and link now. 

Hoping it doesn't deviate from the existing look of the logos.

**Comment by jedmao** [comment]
Thanks for the PR. What do you think, @Pittan?

**Comment by xuhdev** [comment]
I just merged it. No worry!
