### ISSUE TITLE
EditorConfig + Carbon

### ISSUE THREAD

**Issue by sayzlim** [editorconfig/editorconfig.github.com#109]
Hi EditorConfig Team,

@xuhdev told me to make the discussion open, so I’m creating the issue here.

I’m with Carbon from BuySellAds. We’re an ad network that specializes in helping open source projects to generate revenue from display dev/code ads on their sites. Some of the projects that run Carbon on their sites are getbootstrap.com, sequelpro.com, and en.cppreference.com

I decided to reach out because I found that http://editorconfig.org/ is an excellent fit for our dev/code circle. The ad comes with an empty CSS so you can style and place it however you want.

I understand that the project is maintained by several core contributors. Do you mind if I share more details so the team can evaluate whether Carbon is the right option to generate fund for the project?

Thanks,
Sayz

**Comment by jedmao** [comment]
I'm listening.

**Comment by jedmao** [comment]
I'm liking all of these ideas. I'd also be willing to help the NPO process move along.

**Comment by ppalaga** [comment]
+1 for generating revenue, but I do not want to invest my time into founding an NPO at this time.

**Comment by xuhdev** [comment]
@jedmao Shall we move to private discussion regarding the NPO? If anyone else decides to join us later, feel free to shoot me an email and I'll pull you in!

**Comment by jedmao** [comment]
@xuhdev I created an EditorConfig Slack account and invited you to it.

**Comment by xuhdev** [comment]
@sayzlim Would you mind sharing some sample ads? I checked the websites that you listed but I don't see the ads. If you cannot do this publicly, can you send me and @jedmao <jedmao@outlook.com> via email? Thank you!

**Comment by sayzlim** [comment]
@xuhdev do you have any ad blockers extension installed? You can check out these sites in private window mode to view the ads. Otherwise, you can also see this screenshot  to view some of the live ads: https://d.pr/i/quszty

**Only dev/code related ads will be displayed on EditorConfig.**

**Comment by jedmao** [comment]
I can see the ads. They don't look invasive. 👍

**Comment by xuhdev** [comment]
Are three more days enough for everyone to ask @sayzlim any questions? I'll open a voting on this issue after the end of Feb 19 (Hawaii Time).
