### ISSUE TITLE
Sourcehut supports editorconfig

### ISSUE THREAD

**Issue by ddevault** [editorconfig/editorconfig.github.com#111]
https://sourcehut.org

It's used to render indents at your requested width, and to render a ruler at the column limit.

https://git.sr.ht/~sircmpwn/sourcehut.org/tree/master/logo.svg

Cheers :)

**Comment by xuhdev** [comment]
Thanks for the info! Is it builtin or supported by plugin? Can you give a reference page?

**Comment by ddevault** [comment]
It's built-in. There's no docs - it Just Werks.

**Comment by xuhdev** [comment]
@Pittan Mind helping out again :)

**Comment by ddevault** [comment]
@Pittan 先の絵はあなたの？すごい上手だよ！私のロゴも助けってもらってもいいですか？よろしくね :smile:

**Comment by ddevault** [comment]
Thanks :heart:
