### ISSUE TITLE
Put CC BY 3.0 licensing in README

### ISSUE THREAD

**Issue by zbeekman** [editorconfig/editorconfig.github.com#116]
I was looking to see what the licensing of the editorconfig logo was and had to scroll to the very bottom of the EC website to find out. It would be nice to add that info to the logo, and also see if you can get GH to parse a license file to label the project as CC BY 3.0 (if they support that)

**Comment by xuhdev** [comment]
Do you mean the metadata of the logo file?

**Comment by zbeekman** [comment]
I was wondering about the conditions/licensing for re-using the logo file. The https://editorconfig.org says that the website is CC BY 3.0 at the very bottom of the page. I think that the README could also state that the website is CC BY 3.0 so that people browsing the website source (probably to borrow or copy something, in my case the logo) would know what conditions are placed on re-use from browsing the repo.

I'll open a PR, and we can further discuss there.
