### ISSUE TITLE
List jdTextEdit

### ISSUE THREAD

**Issue by JakobDev** [editorconfig/editorconfig.github.com#128]
[jdTextEdit](https://gitlab.com/JakobDev/jdTextEdit) supports .editorconfig out of the box.

**Comment by xuhdev** [comment]
Awesome! Could you show a reference link, please?

**Comment by JakobDev** [comment]
What reference do you mean? I'm the developer of jdTextEdit and it is listed as feature on the linked page.

**Comment by cxw42** [comment]
I see it's in the README - https://gitlab.com/JakobDev/jdTextEdit/-/blob/master/README.md

**Comment by xuhdev** [comment]
Awesome! Thanks! @Pittan Would you mind adding an icon for jdTextEdit? :) Thanks again!
