### ISSUE TITLE
Add Gitea to list of editors

### ISSUE THREAD

**Issue by lafriks** [editorconfig/editorconfig.github.com#129]
Gitea comes with built-in support for editorconfig.

https://gitea.io

**Comment by xuhdev** [comment]
Thanks, awesome!

@Pittan Would you like to draw a new logo :)

![](https://try.gitea.io/img/gitea-lg.png)

Thanks for your long-term support and really appreciate it!

**Comment by xuhdev** [comment]
@lafriks Do you have a reference page for its EditorConfig support?

**Comment by lafriks** [comment]
Sorry just code:
https://github.com/go-gitea/gitea/blob/38cd9ba47b0f9b70e8638f8caf77b3effe50eef4/modules/context/repo.go#L191

We are using github.com/editorconfig/editorconfig-core-go/v2 library

**Comment by lafriks** [comment]
And than based on file path pass options to Monaco JS editor

**Comment by lafriks** [comment]
Thanks
