### ISSUE TITLE
Add GitLab to list of Editors

### ISSUE THREAD

**Issue by phikai** [editorconfig/editorconfig.github.com#132]
GitLab now supports EditorConfig in the Web IDE. You can find docs here: https://docs.gitlab.com/ee/user/project/web_ide/index.html#configure-the-web-ide and release announcement here: https://about.gitlab.com/releases/2020/06/22/gitlab-13-1-released/#editorconfig-support-in-the-web-ide.

It'd be awesome to get GitLab added to the list of supported editors on the site. Let me know if there's anything else you need.

**Comment by xuhdev** [comment]
Thanks, this is great news! @Pittan Had to bother you again... Could you help with a logo? This is how GitLab logo looks like: https://twitter.com/gitlab/photo Thank you so much!

**Comment by Pittan** [comment]
Wow, that's awesome! 
I can start to work on it this weekend!
