### ISSUE TITLE
Add Nova to editors with native support

### ISSUE THREAD

**Issue by sonicdoe** [editorconfig/editorconfig.github.com#134]
[Nova](https://nova.app) supports EditorConfig natively, see the [Nova Library](https://library.panic.com/nova/preferences/#editing).

**Comment by xuhdev** [comment]
Thanks @sonicdoe !

@Pittan Would you mind helping out again? It's totally fine if you don't have time, we can try to find someone else :) Thanks for all the paintings!

**Comment by xuhdev** [comment]
@sonicdoe Do you have a link to an image file of its logo? Seems its website doesn't allow me to download its logo...

**Comment by sonicdoe** [comment]
The icon is at [nova.app/images/nova-app-icon.png](https://nova.app/images/nova-app-icon.png).
