### ISSUE TITLE
Certificate on https://editorconfig.org

### ISSUE THREAD

**Issue by peaverok** [editorconfig/editorconfig.github.com#135]
I am not sure where to put this but when visiting https://editorconfig.org I get:

Network Error (tcp_error)
--
A communication error occurred: ""
The Web Server may be down, too busy, or experiencing other problems preventing it from responding to requests. You may wish to try again at a later time.
For assistance, contact your network support team.

This is entirely because of your certificate. It is showing as invalid and I am a federal government developer and your certificate is  not correct (not sure how) and it is being blocked. I can visit https://editorconfig.org on my home computer just fine. Also, your website is the only website I have visited on my federal government computer that has this problem.

**Comment by greut** [comment]
> my federal government computer

Did you try asking the federal government IT services?

**Comment by xuhdev** [comment]
Closing as non-reproduciable.
