### ISSUE TITLE
Personalized Windows icon based on peoject.

### ISSUE THREAD

**Issue by alex-piccione** [editorconfig/editorconfig.github.com#137]
When I have some projects opened in VS Code I always wonder which Windows I have to open for the specific project.  
The logo is the same and the text is the current file, so I can only see 3-4 same logos with "index.tsx" or "README" but I don't know which one is the UI, the backend or the admin project.
Is there a way to customize the Windows icon based on the project?
If not how can I ask for this feature?

**Comment by xuhdev** [comment]
I'm not sure what you mean, but it sounds like a VS Code specific feature. I would recommend to file a feature request to VS Code.

**Comment by alex-piccione** [comment]
You are right, 
I found the right place.
https://github.com/microsoft/vscode/issues/new?template=feature_request.md

Thanks.
