### ISSUE TITLE
Addition to No Plugin Necessary section

### ISSUE THREAD

**Issue by MakotoE** [editorconfig/editorconfig.github.com#164]
The text editor [EmEditor](https://www.emeditor.com/) recently added EditorConfig support. Is there a criteria for adding an editor to the No Plugin Necessary section? I would like to open a PR to add EmEditor to this list and I wanted to check if you are open to one.

**Comment by Pittan** [comment]
@MakotoE 

Hi! Sorry for the late reply.

> I would like to open a PR to add EmEditor to this list and I wanted to check if you are open to one.

We're welcome to your PR. (Or I can add it for you :) )

**Comment by MakotoE** [comment]
Created PR: https://github.com/editorconfig/editorconfig.github.com/pull/171
