### ISSUE TITLE
Add Neovim to "No Plugin Necessary" list

### ISSUE THREAD

**Issue by brotherkaif** [editorconfig/editorconfig.github.com#172]
Neovim now includes native support for `.editorconfig` files. This feature is also enabled by default, meaning that it is  configured out of the box. [Documentation of this feature can be found here](https://neovim.io/doc/user/editorconfig.html).

Neovim should be added to the "No Plugin Necessary" list on the main page as some Neovim users may not realise that it contains native support and may attempt to install [the Vim plugin](https://github.com/editorconfig/editorconfig-vim#readme).

**Comment by xuhdev** [comment]
@Pittan could you help again? Or, could you suggest some style transformer if it's too much work? Really appreciate your help!
