### ISSUE TITLE
Add Kangaroo to list of Editors

### ISSUE THREAD

**Issue by taozuhong** [editorconfig/editorconfig.github.com#187]
Kangaroo is the first database client tool that support EditorConfig specification:

Kangaroo now supports EditorConfig in the IDE. You can find docs here: [EditorConfig profile](https://www.datatable.online/en/document/editor.html#editorconfig-profile) and release announcement here: https://github.com/dbkangaroo/kangaroo/releases/tag/v5.3.1.240901

It'd be awesome to get Kangaroo added to the list of supported editors on the site. Let me know if there's anything else you need.

**Comment by xuhdev** [comment]
Awesome! Please add it.

**Comment by xuhdev** [comment]
will may need a style transformer or someone to manually turn the logo of Kangaroo to fit the style of the rest of the logos on the page.

I haven't found a good one but feel free to share if you know one :)

**Comment by taozuhong** [comment]
Not have a style of logo like that yet, pls make it, thanks in advance.
