### ISSUE TITLE
Distinguish between native support and plugin-based support

### ISSUE THREAD

**Issue by treyhunner** [editorconfig/editorconfig.github.com#35]
Maybe we should make it more clear that certain editors already have native support.

Maybe we could make the linked logos look different or break them out or have toggle switches to show only some of them?

This might also encourage text editor developers to include native support for EditorConfig.

**Comment by jedmao** [comment]
Interesting idea. On that note, I just [submitted a feature request for Visual Studio Code to add native support](http://visualstudio.uservoice.com/forums/293070-visual-studio-code/suggestions/7758189-support-editorconfig) and I could use your upvotes people!

**Comment by jedmao** [comment]
I would definitely prefer native support for obvious reasons, so I :+1: this request.

**Comment by denofevil** [comment]
:+1:
How about two sections with native ones before plugin-based?

**Comment by treyhunner** [comment]
Done in #38
