### ISSUE TITLE
Can we put CLion logo on the website?

### ISSUE THREAD

**Issue by denofevil** [editorconfig/editorconfig.github.com#37]
The recently released C/C++ IDE from JetBrains also supports EditorConfig via plugin

Link to use for the logo: https://www.jetbrains.com/company/press/materials.html#clion

**Comment by treyhunner** [comment]
I hadn't heard of CLion yet.  I just asked @ineptcat.  We'll try to get a logo up this weekend.

**Comment by denofevil** [comment]
Thank you
