### ISSUE TITLE
Add section for plugins we hope to see

### ISSUE THREAD

**Issue by treyhunner** [editorconfig/editorconfig.github.com#44]
We could call the section "Maybe Someday".  We could instead call it "in-progress" but that might be misleading for plugins that were attempted but then stopped.

I'm not sure whether we should try to list logos in this section or just text links.  @ineptcat draws some of the logos ahead of time, but not all of them because it's hard to tell whether some plugins will ever be done.

Some ideas for what might be in this section:
- [Eclipse](https://github.com/editorconfig/editorconfig/issues/108)
- [LightTable](https://github.com/editorconfig/editorconfig/issues/212)
- [Code](https://visualstudio.uservoice.com/forums/293070-visual-studio-code/suggestions/7758189-support-editorconfig)
- [XCode](https://github.com/editorconfig/editorconfig/issues/194)
- [MonoDevelop](https://github.com/editorconfig/editorconfig/issues/158)
- [Eclipse Orion](https://github.com/editorconfig/editorconfig/issues/142)
- [joe](https://github.com/editorconfig/editorconfig/issues/79)

It seems like this would shed some light on the conversations going on about new plugins.

Thoughts on this?  Would it give too much false hope?

**Comment by ineptcat** [comment]
I'm all for encouraging things to happen. If you think some are more likely to happen (>50%, say) I could draw up a logo and we could put it up as a "preview", or make it really tiny or really faint or something.

**Comment by mikerochip** [comment]
I ended up writing one for MonoDevelop, so at least that one can be taken off the list! Here's the issue: https://github.com/editorconfig/editorconfig/issues/158

Not sure who's attention I need to get to close out that issue though. @treyhunner?

**Comment by cassidyjames** [comment]
We're [working on EditorConfig support](https://github.com/elementary/code/issues/323) in elementary Code! We'd love to be added once [the PR](https://github.com/elementary/code/pull/345) is merged.

Icon:
![icon](https://cdn.rawgit.com/elementary/code/3071aa0039f2c6109e165f737059085933e74685/data/icons/128/io.elementary.code.svg)

**Comment by xuhdev** [comment]
Actually I think this should be closed... @cassidyjames Would you mind opening a new issue? It's easier for us to track. Thanks!
