### ISSUE TITLE
Add Visual Studio Code logo

### ISSUE THREAD

**Issue by treyhunner** [editorconfig/editorconfig.github.com#51]
- [extension](https://marketplace.visualstudio.com/items/chrisdias.vscodeEditorConfig)
- [repository](https://github.com/Microsoft/vscode-editorconfig)

Some questions:

- Does VS Code have a separate logo from Visual Studio?
- What is the status of the VS Code plugin?
- Will we be linking this under the "no plugin necessary" section or the "download a plugin" section?

**Comment by treyhunner** [comment]
@chrisdias any input on the status of the VS Code EditorConfig plugin would be wonderful! 😄

**Comment by jedmao** [comment]
Their logo shape is exactly the same, but I've noticed that the [Visual Studio Code site](https://code.visualstudio.com/) is violet, but the taskbar icon is blue.

The full-blown Visual Studio taskbar icon is a darker violet, see?

![vscode](https://cloud.githubusercontent.com/assets/1058243/11262251/77be01c0-8e42-11e5-928a-f2f6c4097559.png)

You definitely have to install the plugin from within the editor though, which I did earlier today.

**Comment by mitchdenny** [comment]
This can be closed out now. The plug-in now exists and pull request #53 added the links in.

**Comment by chrisdias** [comment]
cool! any chance we can make it say "Visual Studio Code" instead of just "Visual Studio"?  right now there are just 2 visual studio icons side by side and its not clear which is which.

**Comment by mitchdenny** [comment]
Is there an original vector version of the logo with fonts etc, if so I'd be happy to tweak it. Actually @chrisdias, I was going to ask, does the VS team have a generic term to use to describe VS Community/Professional/Enterpise to describe that family of IDE vs. Visual Studio Code?

**Comment by chrisdias** [comment]
The terms are "Visual Studio" for the Windows desktop product (including Community, etc.) and "Visual Studio Code" for our x-plat editor.  So in this case you would have the purple "Visual Studio" and the blue "Visual Studio Code".

Let me see if i can get you vector based versions.

**Comment by jedmao** [comment]
Here's a vector version: https://code.visualstudio.com/Content/images/vscode.ico

**Comment by jedmao** [comment]
Oops! I take that back.

**Comment by jedmao** [comment]
FWIW [visual-studio-code.pdf](https://github.com/editorconfig/editorconfig.github.com/files/79273/visual-studio-code.pdf). GitHub won't let me upload an SVG.

**Comment by mitchdenny** [comment]
I was more thinking the originals for the images that are already there. It seems that there is a distinctive style being used on the site (the images/fonts have a bit of a wobble). So I was hoping to be consistent with that. Who originally came up with the images that are there now?

**Comment by ineptcat** [comment]
Hi, the originals for the images were hand-drawn by me - sorry I've been unresponsive on this thread so far. I can work on a version for Visual Studio Code.

**Comment by mitchdenny** [comment]
@ineptcat - what would be awesome. Thank-you!

**Comment by treyhunner** [comment]
I'm out of town. I'll chime in this weekend.

**Comment by treyhunner** [comment]
I opened a pull request with a new logo and text from @ineptcat: #55. Thoughts?
