### ISSUE TITLE
GNOME Builder also has built-in support

### ISSUE THREAD

**Issue by davidstrauss** [editorconfig/editorconfig.github.com#62]
Can someone update the editor/IDE listings?

**Comment by ffes** [comment]
As you can see on the current website we try to reference a source showing that there is built-in support in that editor. I cannot find it on [their wiki](https://wiki.gnome.org/Apps/Builder/Features), but maybe I look in the wrong place. All I could find is a number of commits including [this one](https://git.gnome.org/browse/gnome-builder/commit/?id=6f1d2a5865555d42f6ffed67042f9e4a52aa6513) where they start using core-c.

What would you suggest to use as link?

And we need to ask Kat On to draw their logo.
@treyhunner I don't know his github username, so can't mention him here

**Comment by treyhunner** [comment]
@ineptcat draws the logos. She can give a time estimate for a new logo. First we should figure out what to link to that notes support.

**Comment by ffes** [comment]
Maybe we can ask @chergert (the main dev op GNOME Builder) to add "Support for EditorConfig" to the [Feature page of their wiki](https://wiki.gnome.org/Apps/Builder/Features), so we can link to that page. Don't know if mentioning him here would be enough. If not I could try IRC or an email as well.

**Comment by chergert** [comment]
No problem. You can use https://wiki.gnome.org/Apps/Builder/Features#EditorConfig for a link.

**Comment by ffes** [comment]
@chergert Thanks a lot!

As soon as there is a drawing of the logo for the site I will prepare a PR

**Comment by ineptcat** [comment]
![gnome_builder_t](https://cloud.githubusercontent.com/assets/2091281/18041460/1eaa5a0a-6d6e-11e6-9fca-2273adcd82c0.png)
@ffes here you go.

**Comment by xuhdev** [comment]
:+1:
