### ISSUE TITLE
Why are plugins required for PhpStorm and PyCharm? (but not for IntelliJ IDEA)

### ISSUE THREAD

**Issue by bittner** [editorconfig/editorconfig.github.com#64]
The website states that [plugins are required](https://github.com/editorconfig/editorconfig.github.com/blob/master/index.html#L154-L155) for the following JetBrains products
- PhpStorm
- PyCharm

but [not for the following](https://github.com/editorconfig/editorconfig.github.com/blob/master/index.html#L127-L132) JetBrains products
- CLion
- RubyMine
- WebStorm
- IntelliJ IDEA.
## Update of Lists Needed?

According to my knowledge all of them build on IntelliJ IDEA. In other words, if there is no plugin needed for IntelliJ IDEA there should be none needed for all other, dependent JetBrains IDEs. -- If this is true PhpStorm and PyCharm need to be moved up to the _"No Plugin Necessary"_ list.
## Update of JetBrains Plugin Description Needed?

In addition, JetBrains' [plugin #7294](https://plugins.jetbrains.com/plugin/7294) states to be _"Compatible with:  PhpStorm , AppCode , CLion , DataGrip , Android Studio"_. Looks like this needs to be clarified with JetBrains. (Why are PyCharm, RubyMine and WebStorm missing in the list?)

**Comment by bittner** [comment]
I've opened [issue PY-20574](https://youtrack.jetbrains.com/issue/PY-20574?query=tag:%20EditorConfig) on YouTrack to clarify part 2 of this issue.

**Comment by xuhdev** [comment]
JetBrain maintains all of their plugins, so we'll just wait for their response...

**Comment by denofevil** [comment]
@bittner, EditorConfig plugin is bundled into WebStorm, RubyMine and IntelliJ IDEA. Thus, it's not needed for these IDEs. Other IDEs, such as PhpStorm and PyCharm don't bundle it, but it can be installed a plugin - that's why it's on the plugins site.
I think only problem here is that CLion is shown in the first list, while it requires a plugin.

**Comment by bittner** [comment]
@denofevil Okay, so the website here needs to be updated. But the [JetBrains plugin's](https://plugins.jetbrains.com/plugin/7294) description also needs to be updated then and include PyCharm, correct?

Interestingly though, PyCharm (2016.2.2) shows the _"EditorConfig is overriding ..."_ message out-of-the-box, i.e. I didn't install any plugin myself. Was this shipped with the recent update?

**Comment by denofevil** [comment]
@bittner oops, sorry, looks like PyCharm is bundling it too, so it should be moved up

**Comment by treyhunner** [comment]
@denofevil so CLion should be moved down and PyCharm should be moved up, right?

**Comment by denofevil** [comment]
@treyhunner yes, that's right

**Comment by xuhdev** [comment]
Are we really going to make this change? This has been delayed for almost one year.

**Comment by xuhdev** [comment]
Seems fixed. Closed now.
