### ISSUE TITLE
Visual studio 2017 supports editorconfig

### ISSUE THREAD

**Issue by awebdeveloper** [editorconfig/editorconfig.github.com#72]
Visual studio 2017 rc1 supports editorconfig out of box.

https://visualstudio.uservoice.com/forums/121579-visual-studio/suggestions/6146845-support-editorconfig

**Comment by xuhdev** [comment]
Let's wait for the final release :)

**Comment by ffes** [comment]
I agree with @xuhdev to wait for the final release of VS2017 to put it on the website.

Also see https://github.com/editorconfig/editorconfig-visualstudio/issues/49

**Comment by ffes** [comment]
And also see #68

**Comment by awebdeveloper** [comment]
Was just bring attention. looks like you ppl are already ahead

**Comment by xuhdev** [comment]
VS 2017 has been released. What should we change here? Visual studio is already in the "No plugin needed" section.

**Comment by ffes** [comment]
I would suggest: All done, so just close this one.
