### ISSUE TITLE
The logo of Gogs is outdated

### ISSUE THREAD

**Issue by jorgesumle** [editorconfig/editorconfig.github.com#76]
This is the new logo: ![logo](https://try.gogs.io/img/favicon.png)

**Comment by xuhdev** [comment]
@ineptcat Can you help out again? Thank you!

**Comment by ineptcat** [comment]
sorry it took a little while - here you go!

![gogs2_t](https://user-images.githubusercontent.com/2091281/27347310-05a1bfce-55a5-11e7-8b21-384b7ac05272.png)

**Comment by xuhdev** [comment]
@ineptcat Awesome, thanks!
