### ISSUE TITLE
KTextEditor (Kate, KWrite, KDevelop, Kile etc.) supports .editorconfig

### ISSUE THREAD

**Issue by mdraw** [editorconfig/editorconfig.github.com#78]
Since https://phabricator.kde.org/D4537 has been merged (into 5.32+, see [merge commit](https://phabricator.kde.org/R39:f9f133b6ac72dfa12bdeeab1a37c5e9dc9a9354e)), KTextEditor supports .editorconfig.
KTextEditor is the text editing component used by ([among others](https://kate-editor.org/2013/11/11/kate-on-5-the-future-of-ktexteditor-and-kate-part/)):
- Kate (https://kate-editor.org/)
- KWrite (https://www.kde.org/applications/utilities/kwrite/)
- KDevelop (https://www.kdevelop.org/)
- Kile (at least 3.0, which is currently in beta: http://kile.sourceforge.net/)

so they all automatically support .editorconfig if they are installed with KTextEditor 5.32.

**Comment by xuhdev** [comment]
@ineptcat Can you help out again? Thank you!

**Comment by ineptcat** [comment]
Thank you for waiting, sorry for the delay! Here's a logo for KTextEditor. Do we need one for the others, that is, Kate, KWrite, KDevelop, Kile ?
![ktexteditor_t](https://user-images.githubusercontent.com/2091281/32857736-b537a65c-c9fd-11e7-80ce-d10ee05c55f5.png)

**Comment by xuhdev** [comment]
@ineptcat Thank you! I think KTextEditor should be OK.
