### ISSUE TITLE
CodeLite supports EditorConfig

### ISSUE THREAD

**Issue by gyrovague** [editorconfig/editorconfig.github.com#79]
CodeLite ( https://codelite.org/ ) has integrated EditorConfig support since Dec 2016, see last post here: https://github.com/eranif/codelite/issues/1046

CodeLite should therefore be added to the list of supported editors on the http://editorconfig.org/ main website. It seems to be implemented as a plugin (i.e. accessible under the "Plugins" main menu option), but it is included and enabled by default in CodeLite installation (so doesn't require a separate plugin to download or configure), so I would guess it would be more appropriate to list under the "No Plugin Necessary" section.

**Comment by treyhunner** [comment]
I agree that this should be in the No Plugin Necessary section.

What should be used as the logo?

@ineptcat would you mind drawing a logo for CodeLite?

**Comment by gyrovague** [comment]
I don't really know what the appropriate logo is, I guess best would be to reach out to CodeLite devs and ask? The main site seems to have that silver dragon logo, but the app icon (and website favicon) has a much simpler/cleaner 3 coloured blocks thing
![image](https://user-images.githubusercontent.com/1925426/31929041-9e791190-b89a-11e7-8e95-a23e59e93125.png)

**Comment by ineptcat** [comment]
Thanks for your patience!
![codelite_t](https://user-images.githubusercontent.com/2091281/32857250-05a016f8-c9fc-11e7-8473-f2074c4b36bc.png)

**Comment by xuhdev** [comment]
Added: a5c7c192e49be7b3f5a05dd3242244e755e3aea7

Thank you all!
