### ISSUE TITLE
List ec4j as EditorConfig Java library

### ISSUE THREAD

**Issue by ppalaga** [editorconfig/editorconfig.github.com#81]
@xuhdev could we please get a link to https://github.com/ec4j/ec4j ?

**Comment by xuhdev** [comment]
Awesome!! Thanks!!

**Comment by ppalaga** [comment]
Thanks, could you please add Angelo Zerr https://github.com/angelozerr as the co-author of ec4j?

**Comment by xuhdev** [comment]
Thanks, done
