### ISSUE TITLE
List editorconfig-maven-plugin

### ISSUE THREAD

**Issue by ppalaga** [editorconfig/editorconfig.github.com#82]
@xuhdev could you please list the brand new editorconfig-maven-plugin?
The link is  http://ec4j.github.io/editorconfig-maven-plugin/ and I am the sole author.

**Comment by xuhdev** [comment]
Sure. Which section do you think it should be added? Maybe editors? We need a new logo again. Can you help out, @ineptcat and @Pittan? :smile:

**Comment by ppalaga** [comment]
> Which section do you think it should be added? Maybe editors?

Maven is a build tool rather than an editor. editorconfig-maven-plugin helps to detect formatting violations and eventually fix them too. I'd say it falls under a broader category of headless tools. `editorconfig-tools` npm package [1] seems to do the same thing.

If you do not want to introduce the "headless tools" category for now, I do not mind editorconfig-maven-plugin to be listed under editors.

https://www.npmjs.com/package/editorconfig-tools

**Comment by Pittan** [comment]
@xuhdev Sure :) 
@ppalaga> Is there any logos?

**Comment by ppalaga** [comment]
> Is there any logos?

If you mean Maven logo, this is I think, the most recent one http://maven.apache.org/images/maven-logo-black-on-white.png
editorconfig-maven-plugin has no logo.

**Comment by xuhdev** [comment]
@Pittan Thanks!
@ppalaga Actually, why not extract the checking and enforcing code in the plugin, so we can use it elsewhere? And I also agree that this is not a traditional editor plugin. I think we can add a headless tool section.

**Comment by ppalaga** [comment]
> why not extract the checking and enforcing code

I am about do that so that I can re-use it in a Gradle plugin

**Comment by Pittan** [comment]
How do I add Maven logo?
Should I add a image only?

**Comment by xuhdev** [comment]
@Pittan Awesome! For your convenience, you can just upload the logo here in png format :)

**Comment by xuhdev** [comment]
@Pittan Or, if you like, you can make a PR directly

**Comment by Pittan** [comment]
@ppalaga  I made a PR 😀

**Comment by xuhdev** [comment]
Solved in 477a7accd843c7a04bd07c1d97887a7b67299af8 , thank you all for the Maven plugin @ppalaga and for the logo @Pittan !
