### ISSUE TITLE
List MonoDevelop

### ISSUE THREAD

**Issue by xuhdev** [editorconfig/editorconfig.github.com#85]
An MonoDevelop plugin has been made available at https://github.com/mikerochip/editorconfig-monodevelop by @mikerochip (Thanks and great work!)

@ineptcat @Pittan Would you like to help out with the icon again :smiley: ? Many thanks!

Also see editorconfig/editorconfig#158

**Comment by mhutch** [comment]
Note also that MonoDevelop 7.5+ (currently in preview) has editorconfig built in.

**Comment by mikerochip** [comment]
Thanks @xuhdev! Either through my plugin or the official 7.5 release, MonoDevelop and Visual Studio for Mac now have support from this point forward, so no need to stop icon creation and plugin listing.

**Comment by Pittan** [comment]
Okay, new icon coming...🚚
Do I have to draw MonoDevelop and VS for Mac(Maybe it can use the Original VS icon)

**Comment by xuhdev** [comment]
@Pittan I think MonoDevelop should be good enough... VS icon can be used cross-platform.

**Comment by mikerochip** [comment]
@xuhdev @Pittan My suggestion would be:
* 2 new icons that both link to the same place.
* The Visual Studio for Mac icon can use the same graphic as Visual Studio but the text should say "Visual Studio for Mac"

The problem with re-using the existing Visual Studio icon is that the Visual Studio for Mac plugin is the same as the MonoDevelop plugin, it is not the Visual Studio plugin.

Hope that makes sense.

**Comment by xuhdev** [comment]
Hmm, how about put both in the same image, and divide them using a dashed vertical line?

**Comment by mikerochip** [comment]
That's a really cool idea!

**Comment by jedmao** [comment]
Or a diagonal line.

**Comment by xuhdev** [comment]
Closed in 1d478b0349921da163f60951272ae65837c595b9

**Comment by mikerochip** [comment]
It looks awesome! Thank you again @xuhdev and @Pittan!
