### ISSUE TITLE
Add elementary Code

### ISSUE THREAD

**Issue by cassidyjames** [editorconfig/editorconfig.github.com#86]
We're [working on EditorConfig support](https://github.com/elementary/code/issues/323) in [elementary Code](https://github.com/elementary/code)! We'd love to be added once [the PR](https://github.com/elementary/code/pull/345) is merged.

Icon:
![icon](https://cdn.rawgit.com/elementary/code/3071aa0039f2c6109e165f737059085933e74685/data/icons/128/io.elementary.code.svg)

**Comment by treyhunner** [comment]
@Pittan would you be interested in drawing a version of this icon by any chance? 🙂
