### ISSUE TITLE
XCode Plugin is Dead

### ISSUE THREAD

**Issue by dodekeract** [editorconfig/editorconfig.github.com#89]
Link should be removed. Current `http://alcatraz.io` website can be bought and potentially be used to infect people with malware, thinking they'll download a legitimate editorconfig plugin.

**Comment by xuhdev** [comment]
Where is this link?

**Comment by ffes** [comment]
As @xuhdev says, the link to the XCode editorconfig plugin on the website is `https://github.com/MarcoSero/EditorConfig-Xcode`. Don't see the link you mention. But I'm AFK and maybe we both missed something.

**Comment by ffes** [comment]
Indeed it seems that Xcode "Plugins" are dead and are replaced by "Extensions".

https://github.com/MarcoSero/EditorConfig-Xcode/issues/6

https://medium.com/rocknnull/xcode-8-plugins-alcatraz-the-end-of-an-era-ea6e63617d14

So let's remove the link to this plugin. But keep the icon, maybe EditorConfig will work in Xcode (already or in the future)
