### ISSUE TITLE
Mark MonoDevelop/VSMac as "No Plugin Necessary"

### ISSUE THREAD

**Issue by mhutch** [editorconfig/editorconfig.github.com#90]
As of the 7.5 release last week, Visual Studio for Mac and MonoDevelop support editorconfig natively.

**Comment by xuhdev** [comment]
Thanks! Can you give us a hint? I actually cannot find any info on the plugin website...

**Comment by mhutch** [comment]
See the release notes at https://docs.microsoft.com/en-us/visualstudio/releasenotes/vs2017-mac-relnotes

**Comment by xuhdev** [comment]
Indeed, thanks!

**Comment by mhutch** [comment]
Thanks! One minor clarification - it doesn't use the plugin, it's part of the core. The plugin it still useful for older versions though.
