### ISSUE TITLE
List editorconfig-gradle-plugin and editorconfig-ant-tasks

### ISSUE THREAD

**Issue by ppalaga** [editorconfig/editorconfig.github.com#98]
Gradle and Apache Ant are Java build tools much like Apache Maven. Please list the new plugins for Gradle https://github.com/ec4j/editorconfig-gradle-plugin and Apache Ant https://github.com/ec4j/editorconfig-ant-tasks under the headless tools.

**Comment by xuhdev** [comment]
@Pittan  Can you help us again? Thanks!
