### ISSUE TITLE
Code Crusader now supports EditorConfig

### ISSUE THREAD

**Issue by jafl** [editorconfig/editorconfig.github.com#99]
I just released an update for Code Crusader that adds support for .editorconfig files.  The homepage is https://sourceforge.net/projects/codecrusader/

**Comment by treyhunner** [comment]
Does Code Crusader have a logo?

**Comment by jafl** [comment]
Yes:  https://sourceforge.net/p/codecrusader/icon?1539277845

**Comment by xuhdev** [comment]
@Pittan Can you help out again? Thanks! :smile:
